name: Konwerter48749

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 0'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install pyinstaller
      
      - name: Install json library in python
        run: pip install json
      
      - name: Install pyyaml library in python
        run: pip install pyyaml
      
      - name: Build EXE
        run: pyinstaller --onefile --name Konwerter Konwerter.py

      - name: Upload EXE
        uses: actions/upload-artifact@v2
        with:
          name: Konwerter-exe
          path: dist/Konwerter.exe
